apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    tier: frontend
  annotations:
    description: "This is a sample Nginx Pod for demonstration purposes."
spec:
  # 重启策略：Always、OnFailure、Never
  restartPolicy: Always

  # 容器定义
  containers:
    - name: nginx-container
      image: nginx:1.23.1
      imagePullPolicy: IfNotPresent

      # 容器端口
      ports:
        - containerPort: 80
          protocol: TCP

      # 环境变量
      env:
        - name: ENV_NAME
          value: "production"
        - name: ENV_VERSION
          value: "1.0.0"

      # 资源限制
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"

      # 健康检查
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10

      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10

      # 卷挂载
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: nginx-logs
          mountPath: /var/log/nginx

  # 卷定义
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-configmap
    - name: nginx-logs
      emptyDir: {}