version: '3.4'

services:
  db:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: andrew
      MYSQL_PASSWORD: andrew
    ports:
      - "3306:3306" # 宿主机的3306端口映射到容器的3306端口
    volumes:
      - db_data:/var/lib/mysql
#    restart: always

# 使用doker volume进行数据持久化
volumes:
  db_data:







