apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-storage-pv
  namespace: base-services
spec:
  storageClassName: prometheus-db-vol
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/prometheus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-db
  namespace: base-services
spec:
  storageClassName: prometheus-db-vol
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

--- 
apiVersion: storage.k8s.io/v1
kind: storageClass
metadata:
  name: prometheus-db-vol
provisioner: kubernetes.io/no-provisioner
volumeBindingMole: WaitforFirstConsumer