:toc:

// 保证所有的目录层级都可以正常显示图片
:path: linux/
:imagesdir: ../image/

// 只有book调用的时候才会走到这里
ifdef::rootpath[]
:imagesdir: {rootpath}{path}{imagesdir}
endif::rootpath[]


== linux常见问题及排查手段


=== CPU


=== 内存

=== 内存缺页

在 Linux 系统中，缺页中断（Page Fault）是操作系统内存管理中的一个重要概念。当程序试图访问一个不在物理内存中的页面时，就会发生缺页中断。根据页面是否需要从磁盘加载到内存，缺页中断可以分为两种类型：主缺页（Major Page Fault）和次缺页（Minor Page Fault）。

==== 主缺页（Major Page Fault）

- **定义**：主缺页指的是那些需要从磁盘（如交换分区或文件系统）读取数据到物理内存的缺页中断。
- **特点**：
- 这种类型的缺页处理时间较长，因为它涉及到磁盘I/O操作。
- 发生主缺页通常是因为被访问的数据之前已经被换出到了交换空间或者从未被加载进内存过。
- **影响**：主缺页对性能的影响较大，因为磁盘I/O的速度远低于内存访问速度。

==== 次缺页（Minor Page Fault）

- **定义**：次缺页是指那些不需要从磁盘读取数据，而可以直接通过调整内存映射就能解决的缺页中断。
- **特点**：
- 这类缺页一般只需要在内存内部进行一些调整即可满足请求，例如将数据从其他部分的物理内存移动到所需位置。
- 处理速度相对较快，因为它不涉及磁盘I/O操作。
- **常见情况**：次缺页常常发生在程序启动初期，当程序开始运行并首次访问分配给它的内存区域时。

==== 查看进程的缺页信息

在 Linux 中，可以通过读取 `/proc/[pid]/stat` 文件来获取特定进程的缺页统计信息。其中，第12个字段表示的是次缺页次数（minflt），第13个字段表示的是主缺页次数（majflt）。

此外，使用 `ps`, `top` 或者 `vmstat` 等命令行工具也可以查看相关的信息。例如，使用 `ps` 命令：

[source,bash]
----
# 查看所有进程的缺页信息 ps -eo min_flt,maj_flt,cmd|more
ps -o min_flt,maj_flt,pid,cmd -p <PID>
# 查看进程每秒主缺页和次缺页
pidstat -rm -f ./path/file
----

这条命令会输出指定 PID 的进程的次缺页数、主缺页数、进程ID以及执行的命令。

理解主缺页和次缺页的区别有助于分析和优化程序的内存使用情况，尤其是对于那些对性能要求较高的应用程序来说，减少主缺页的发生可以显著提高程序的执行效率。




=== 网络


=== I/O



