version: '3.4'

services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - redis-master-data:/data
    networks:
      - redis-network
    command: redis-server --appendonly yes  # 开启持久化
    restart: unless-stopped

  redis-slave1:
    image: redis:latest
    container_name: redis-slave1
    ports:
      - "6380:6379"
    volumes:
      - redis-slave1-data:/data
    networks:
      - redis-network
    command: redis-server --appendonly yes --replicaof redis-master 6379
    restart: unless-stopped

  redis-slave2:
    image: redis:latest
    container_name: redis-slave2
    ports:
      - "6381:6379"
    volumes:
      - redis-slave2-data:/data
    networks:
      - redis-network
    command: redis-server --appendonly yes --replicaof redis-master 6379
    restart: unless-stopped

volumes:
  redis-master-data:
  redis-slave1-data:
  redis-slave2-data:

networks:
  redis-network:
    driver: bridge