version: '3.4'

services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - redis-master-data:/data
    networks:
      - redis-network
    command: redis-server --appendonly yes  # 开启持久化
    restart: unless-stopped

  redis-slave1:
    image: redis:latest
    container_name: redis-slave1
    ports:
      - "6380:6379"
    volumes:
      - redis-slave1-data:/data
    networks:
      - redis-network
    command: redis-server --appendonly yes --replicaof redis-master 6379
    restart: unless-stopped

  redis-slave2:
    image: redis:latest
    container_name: redis-slave2
    ports:
      - "6381:6379"
    volumes:
      - redis-slave2-data:/data
    networks:
      - redis-network
    command: redis-server --appendonly yes --replicaof redis-master 6379
    restart: unless-stopped

# 使用docker volume ls 查看挂载的卷
volumes:
  redis-master-data:
  redis-slave1-data:
  redis-slave2-data:

# 只有创建自定义网络之后，各个容器才能使用域名进行通讯
# 使用doker network create redis-network也能创建自定义网络
networks:
  redis-network:
    driver: bridge